name: Check PRdoc

on:
  pull_request:
    types: [labeled, opened, synchronize, unlabeled]

env:
  IMAGE: paritytech/prdoc:latest
  API_BASE: https://api.github.com/repos
  REPO: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PR: ${{ github.event.pull_request.number }}
  ENGINE: docker

jobs:
  check-prdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: |
          echo "Pulling $IMAGE"
          docker pull $IMAGE
          docker run --rm -v $PWD:/repo $IMAGE --version

      - name: Check if PRdoc is required
        id: get-labels
        run: |
          # Fetch the labels for the PR under test
          echo "Fetch the labels for $API_BASE/${REPO}/pulls/${GITHUB_PR}"
          labels=$( curl -H "Authorization: token ${GITHUB_TOKEN}" -s "$API_BASE/${REPO}/pulls/${GITHUB_PR}" | jq '.labels | .[] | .name' | tr "\n" ",")
          echo "Labels: ${labels}"
          echo "labels=${labels}" >> "$GITHUB_OUTPUT"

      # TODO: Here we should check if the prdoc is valid in case the user added one nonetheless
      - name: Early exit if PR is silent
        if: ${{ contains(steps.get-labels.outputs.labels, 'R0') }}
        run: |
          echo "PR detected as silent, no PRDoc is required, exiting..."
          exit 0

      - name: Checkout repo
        if: ${{ !contains(steps.get-labels.outputs.labels, 'R0') }}
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - name: PRdoc check for PR#${{ github.event.pull_request.number }}
        if: ${{ !contains(steps.get-labels.outputs.labels, 'R0') }}
        run: |
          echo "Checking for PR#${GITHUB_PR}"
          $ENGINE run --rm -v $PWD:/repo $IMAGE check -n ${GITHUB_PR} || true
